/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthMagicRouteImport } from './routes/auth/magic'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authResetEmailSentRouteImport } from './routes/(auth)/reset-email-sent'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authMagicLoginRouteImport } from './routes/(auth)/magic-login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTrackedPostsIndexRouteImport } from './routes/_authenticated/tracked-posts/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSheetIndexRouteImport } from './routes/_authenticated/sheet/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedKnowledgeBaseIndexRouteImport } from './routes/_authenticated/knowledge-base/index'
import { Route as AuthenticatedKeywordsIndexRouteImport } from './routes/_authenticated/keywords/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedFollowingsIndexRouteImport } from './routes/_authenticated/followings/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAutoActionsIndexRouteImport } from './routes/_authenticated/auto-actions/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as AuthenticatedSettingsCommentsRouteImport } from './routes/_authenticated/settings/comments'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccessRouteImport } from './routes/_authenticated/settings/access'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedTrackedPostsNewRouteRouteImport } from './routes/_authenticated/tracked-posts/new/route'
import { Route as AuthenticatedKeywordsKeywordIdRouteRouteImport } from './routes/_authenticated/keywords/$keywordId/route'
import { Route as AuthenticatedFollowingsNewRouteRouteImport } from './routes/_authenticated/followings/new/route'
import { Route as AuthenticatedTrackedPostsNewIndexRouteImport } from './routes/_authenticated/tracked-posts/new/index'
import { Route as AuthenticatedKeywordsKeywordIdIndexRouteImport } from './routes/_authenticated/keywords/$keywordId/index'
import { Route as AuthenticatedFollowingsNewIndexRouteImport } from './routes/_authenticated/followings/new/index'
import { Route as AuthenticatedTrackedPostsNewAutoReplyRouteImport } from './routes/_authenticated/tracked-posts/new/auto-reply'
import { Route as AuthenticatedTrackedPostsNewAutoReactRouteImport } from './routes/_authenticated/tracked-posts/new/auto-react'
import { Route as AuthenticatedKeywordsKeywordIdMonitoringRouteImport } from './routes/_authenticated/keywords/$keywordId/monitoring'
import { Route as AuthenticatedKeywordsKeywordIdAutoReactRouteImport } from './routes/_authenticated/keywords/$keywordId/auto-react'
import { Route as AuthenticatedKeywordsKeywordIdAutoCommentRouteImport } from './routes/_authenticated/keywords/$keywordId/auto-comment'
import { Route as AuthenticatedFollowingsNewReactPostsRouteImport } from './routes/_authenticated/followings/new/react-posts'
import { Route as AuthenticatedFollowingsNewMonitoringRouteImport } from './routes/_authenticated/followings/new/monitoring'
import { Route as AuthenticatedFollowingsNewAutoCommentRouteImport } from './routes/_authenticated/followings/new/auto-comment'
import { Route as AuthenticatedTrackedPostsPostIdSettingsRouteRouteImport } from './routes/_authenticated/tracked-posts/$postId/settings/route'
import { Route as AuthenticatedFollowingsChannelIdSettingsRouteRouteImport } from './routes/_authenticated/followings/$channelId/settings/route'
import { Route as AuthenticatedTrackedPostsPostIdSettingsIndexRouteImport } from './routes/_authenticated/tracked-posts/$postId/settings/index'
import { Route as AuthenticatedFollowingsChannelIdSettingsIndexRouteImport } from './routes/_authenticated/followings/$channelId/settings/index'
import { Route as AuthenticatedTrackedPostsPostIdSettingsAutoReplyRouteImport } from './routes/_authenticated/tracked-posts/$postId/settings/auto-reply'
import { Route as AuthenticatedTrackedPostsPostIdSettingsAutoReactRouteImport } from './routes/_authenticated/tracked-posts/$postId/settings/auto-react'
import { Route as AuthenticatedFollowingsChannelIdSettingsReactPostsRouteImport } from './routes/_authenticated/followings/$channelId/settings/react-posts'
import { Route as AuthenticatedFollowingsChannelIdSettingsMonitoringRouteImport } from './routes/_authenticated/followings/$channelId/settings/monitoring'
import { Route as AuthenticatedFollowingsChannelIdSettingsAutoCommentRouteImport } from './routes/_authenticated/followings/$channelId/settings/auto-comment'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthMagicRoute = AuthMagicRouteImport.update({
  id: '/auth/magic',
  path: '/auth/magic',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetEmailSentRoute = authResetEmailSentRouteImport.update({
  id: '/(auth)/reset-email-sent',
  path: '/reset-email-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authMagicLoginRoute = authMagicLoginRouteImport.update({
  id: '/(auth)/magic-login',
  path: '/magic-login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrackedPostsIndexRoute =
  AuthenticatedTrackedPostsIndexRouteImport.update({
    id: '/tracked-posts/',
    path: '/tracked-posts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSheetIndexRoute = AuthenticatedSheetIndexRouteImport.update({
  id: '/sheet/',
  path: '/sheet/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeBaseIndexRoute =
  AuthenticatedKnowledgeBaseIndexRouteImport.update({
    id: '/knowledge-base/',
    path: '/knowledge-base/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeywordsIndexRoute =
  AuthenticatedKeywordsIndexRouteImport.update({
    id: '/keywords/',
    path: '/keywords/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFollowingsIndexRoute =
  AuthenticatedFollowingsIndexRouteImport.update({
    id: '/followings/',
    path: '/followings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutoActionsIndexRoute =
  AuthenticatedAutoActionsIndexRouteImport.update({
    id: '/auto-actions/',
    path: '/auto-actions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsCommentsRoute =
  AuthenticatedSettingsCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccessRoute =
  AuthenticatedSettingsAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrackedPostsNewRouteRoute =
  AuthenticatedTrackedPostsNewRouteRouteImport.update({
    id: '/tracked-posts/new',
    path: '/tracked-posts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeywordsKeywordIdRouteRoute =
  AuthenticatedKeywordsKeywordIdRouteRouteImport.update({
    id: '/keywords/$keywordId',
    path: '/keywords/$keywordId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFollowingsNewRouteRoute =
  AuthenticatedFollowingsNewRouteRouteImport.update({
    id: '/followings/new',
    path: '/followings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrackedPostsNewIndexRoute =
  AuthenticatedTrackedPostsNewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTrackedPostsNewRouteRoute,
  } as any)
const AuthenticatedKeywordsKeywordIdIndexRoute =
  AuthenticatedKeywordsKeywordIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKeywordsKeywordIdRouteRoute,
  } as any)
const AuthenticatedFollowingsNewIndexRoute =
  AuthenticatedFollowingsNewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFollowingsNewRouteRoute,
  } as any)
const AuthenticatedTrackedPostsNewAutoReplyRoute =
  AuthenticatedTrackedPostsNewAutoReplyRouteImport.update({
    id: '/auto-reply',
    path: '/auto-reply',
    getParentRoute: () => AuthenticatedTrackedPostsNewRouteRoute,
  } as any)
const AuthenticatedTrackedPostsNewAutoReactRoute =
  AuthenticatedTrackedPostsNewAutoReactRouteImport.update({
    id: '/auto-react',
    path: '/auto-react',
    getParentRoute: () => AuthenticatedTrackedPostsNewRouteRoute,
  } as any)
const AuthenticatedKeywordsKeywordIdMonitoringRoute =
  AuthenticatedKeywordsKeywordIdMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedKeywordsKeywordIdRouteRoute,
  } as any)
const AuthenticatedKeywordsKeywordIdAutoReactRoute =
  AuthenticatedKeywordsKeywordIdAutoReactRouteImport.update({
    id: '/auto-react',
    path: '/auto-react',
    getParentRoute: () => AuthenticatedKeywordsKeywordIdRouteRoute,
  } as any)
const AuthenticatedKeywordsKeywordIdAutoCommentRoute =
  AuthenticatedKeywordsKeywordIdAutoCommentRouteImport.update({
    id: '/auto-comment',
    path: '/auto-comment',
    getParentRoute: () => AuthenticatedKeywordsKeywordIdRouteRoute,
  } as any)
const AuthenticatedFollowingsNewReactPostsRoute =
  AuthenticatedFollowingsNewReactPostsRouteImport.update({
    id: '/react-posts',
    path: '/react-posts',
    getParentRoute: () => AuthenticatedFollowingsNewRouteRoute,
  } as any)
const AuthenticatedFollowingsNewMonitoringRoute =
  AuthenticatedFollowingsNewMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedFollowingsNewRouteRoute,
  } as any)
const AuthenticatedFollowingsNewAutoCommentRoute =
  AuthenticatedFollowingsNewAutoCommentRouteImport.update({
    id: '/auto-comment',
    path: '/auto-comment',
    getParentRoute: () => AuthenticatedFollowingsNewRouteRoute,
  } as any)
const AuthenticatedTrackedPostsPostIdSettingsRouteRoute =
  AuthenticatedTrackedPostsPostIdSettingsRouteRouteImport.update({
    id: '/tracked-posts/$postId/settings',
    path: '/tracked-posts/$postId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFollowingsChannelIdSettingsRouteRoute =
  AuthenticatedFollowingsChannelIdSettingsRouteRouteImport.update({
    id: '/followings/$channelId/settings',
    path: '/followings/$channelId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrackedPostsPostIdSettingsIndexRoute =
  AuthenticatedTrackedPostsPostIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTrackedPostsPostIdSettingsRouteRoute,
  } as any)
const AuthenticatedFollowingsChannelIdSettingsIndexRoute =
  AuthenticatedFollowingsChannelIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFollowingsChannelIdSettingsRouteRoute,
  } as any)
const AuthenticatedTrackedPostsPostIdSettingsAutoReplyRoute =
  AuthenticatedTrackedPostsPostIdSettingsAutoReplyRouteImport.update({
    id: '/auto-reply',
    path: '/auto-reply',
    getParentRoute: () => AuthenticatedTrackedPostsPostIdSettingsRouteRoute,
  } as any)
const AuthenticatedTrackedPostsPostIdSettingsAutoReactRoute =
  AuthenticatedTrackedPostsPostIdSettingsAutoReactRouteImport.update({
    id: '/auto-react',
    path: '/auto-react',
    getParentRoute: () => AuthenticatedTrackedPostsPostIdSettingsRouteRoute,
  } as any)
const AuthenticatedFollowingsChannelIdSettingsReactPostsRoute =
  AuthenticatedFollowingsChannelIdSettingsReactPostsRouteImport.update({
    id: '/react-posts',
    path: '/react-posts',
    getParentRoute: () => AuthenticatedFollowingsChannelIdSettingsRouteRoute,
  } as any)
const AuthenticatedFollowingsChannelIdSettingsMonitoringRoute =
  AuthenticatedFollowingsChannelIdSettingsMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedFollowingsChannelIdSettingsRouteRoute,
  } as any)
const AuthenticatedFollowingsChannelIdSettingsAutoCommentRoute =
  AuthenticatedFollowingsChannelIdSettingsAutoCommentRouteImport.update({
    id: '/auto-comment',
    path: '/auto-comment',
    getParentRoute: () => AuthenticatedFollowingsChannelIdSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/magic-login': typeof authMagicLoginRoute
  '/otp': typeof authOtpRoute
  '/reset-email-sent': typeof authResetEmailSentRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/magic': typeof AuthMagicRoute
  '/followings/new': typeof AuthenticatedFollowingsNewRouteRouteWithChildren
  '/keywords/$keywordId': typeof AuthenticatedKeywordsKeywordIdRouteRouteWithChildren
  '/tracked-posts/new': typeof AuthenticatedTrackedPostsNewRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/settings/access': typeof AuthenticatedSettingsAccessRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/comments': typeof AuthenticatedSettingsCommentsRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/auto-actions/': typeof AuthenticatedAutoActionsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/followings/': typeof AuthenticatedFollowingsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/keywords/': typeof AuthenticatedKeywordsIndexRoute
  '/knowledge-base/': typeof AuthenticatedKnowledgeBaseIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/sheet/': typeof AuthenticatedSheetIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/tracked-posts/': typeof AuthenticatedTrackedPostsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/followings/$channelId/settings': typeof AuthenticatedFollowingsChannelIdSettingsRouteRouteWithChildren
  '/tracked-posts/$postId/settings': typeof AuthenticatedTrackedPostsPostIdSettingsRouteRouteWithChildren
  '/followings/new/auto-comment': typeof AuthenticatedFollowingsNewAutoCommentRoute
  '/followings/new/monitoring': typeof AuthenticatedFollowingsNewMonitoringRoute
  '/followings/new/react-posts': typeof AuthenticatedFollowingsNewReactPostsRoute
  '/keywords/$keywordId/auto-comment': typeof AuthenticatedKeywordsKeywordIdAutoCommentRoute
  '/keywords/$keywordId/auto-react': typeof AuthenticatedKeywordsKeywordIdAutoReactRoute
  '/keywords/$keywordId/monitoring': typeof AuthenticatedKeywordsKeywordIdMonitoringRoute
  '/tracked-posts/new/auto-react': typeof AuthenticatedTrackedPostsNewAutoReactRoute
  '/tracked-posts/new/auto-reply': typeof AuthenticatedTrackedPostsNewAutoReplyRoute
  '/followings/new/': typeof AuthenticatedFollowingsNewIndexRoute
  '/keywords/$keywordId/': typeof AuthenticatedKeywordsKeywordIdIndexRoute
  '/tracked-posts/new/': typeof AuthenticatedTrackedPostsNewIndexRoute
  '/followings/$channelId/settings/auto-comment': typeof AuthenticatedFollowingsChannelIdSettingsAutoCommentRoute
  '/followings/$channelId/settings/monitoring': typeof AuthenticatedFollowingsChannelIdSettingsMonitoringRoute
  '/followings/$channelId/settings/react-posts': typeof AuthenticatedFollowingsChannelIdSettingsReactPostsRoute
  '/tracked-posts/$postId/settings/auto-react': typeof AuthenticatedTrackedPostsPostIdSettingsAutoReactRoute
  '/tracked-posts/$postId/settings/auto-reply': typeof AuthenticatedTrackedPostsPostIdSettingsAutoReplyRoute
  '/followings/$channelId/settings/': typeof AuthenticatedFollowingsChannelIdSettingsIndexRoute
  '/tracked-posts/$postId/settings/': typeof AuthenticatedTrackedPostsPostIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/magic-login': typeof authMagicLoginRoute
  '/otp': typeof authOtpRoute
  '/reset-email-sent': typeof authResetEmailSentRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/auth/magic': typeof AuthMagicRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/settings/access': typeof AuthenticatedSettingsAccessRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/comments': typeof AuthenticatedSettingsCommentsRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/auto-actions': typeof AuthenticatedAutoActionsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/followings': typeof AuthenticatedFollowingsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/keywords': typeof AuthenticatedKeywordsIndexRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/sheet': typeof AuthenticatedSheetIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/tracked-posts': typeof AuthenticatedTrackedPostsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/followings/new/auto-comment': typeof AuthenticatedFollowingsNewAutoCommentRoute
  '/followings/new/monitoring': typeof AuthenticatedFollowingsNewMonitoringRoute
  '/followings/new/react-posts': typeof AuthenticatedFollowingsNewReactPostsRoute
  '/keywords/$keywordId/auto-comment': typeof AuthenticatedKeywordsKeywordIdAutoCommentRoute
  '/keywords/$keywordId/auto-react': typeof AuthenticatedKeywordsKeywordIdAutoReactRoute
  '/keywords/$keywordId/monitoring': typeof AuthenticatedKeywordsKeywordIdMonitoringRoute
  '/tracked-posts/new/auto-react': typeof AuthenticatedTrackedPostsNewAutoReactRoute
  '/tracked-posts/new/auto-reply': typeof AuthenticatedTrackedPostsNewAutoReplyRoute
  '/followings/new': typeof AuthenticatedFollowingsNewIndexRoute
  '/keywords/$keywordId': typeof AuthenticatedKeywordsKeywordIdIndexRoute
  '/tracked-posts/new': typeof AuthenticatedTrackedPostsNewIndexRoute
  '/followings/$channelId/settings/auto-comment': typeof AuthenticatedFollowingsChannelIdSettingsAutoCommentRoute
  '/followings/$channelId/settings/monitoring': typeof AuthenticatedFollowingsChannelIdSettingsMonitoringRoute
  '/followings/$channelId/settings/react-posts': typeof AuthenticatedFollowingsChannelIdSettingsReactPostsRoute
  '/tracked-posts/$postId/settings/auto-react': typeof AuthenticatedTrackedPostsPostIdSettingsAutoReactRoute
  '/tracked-posts/$postId/settings/auto-reply': typeof AuthenticatedTrackedPostsPostIdSettingsAutoReplyRoute
  '/followings/$channelId/settings': typeof AuthenticatedFollowingsChannelIdSettingsIndexRoute
  '/tracked-posts/$postId/settings': typeof AuthenticatedTrackedPostsPostIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/magic-login': typeof authMagicLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-email-sent': typeof authResetEmailSentRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/auth/magic': typeof AuthMagicRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/followings/new': typeof AuthenticatedFollowingsNewRouteRouteWithChildren
  '/_authenticated/keywords/$keywordId': typeof AuthenticatedKeywordsKeywordIdRouteRouteWithChildren
  '/_authenticated/tracked-posts/new': typeof AuthenticatedTrackedPostsNewRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/settings/access': typeof AuthenticatedSettingsAccessRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/comments': typeof AuthenticatedSettingsCommentsRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/auto-actions/': typeof AuthenticatedAutoActionsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/followings/': typeof AuthenticatedFollowingsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/keywords/': typeof AuthenticatedKeywordsIndexRoute
  '/_authenticated/knowledge-base/': typeof AuthenticatedKnowledgeBaseIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/sheet/': typeof AuthenticatedSheetIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/tracked-posts/': typeof AuthenticatedTrackedPostsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/followings/$channelId/settings': typeof AuthenticatedFollowingsChannelIdSettingsRouteRouteWithChildren
  '/_authenticated/tracked-posts/$postId/settings': typeof AuthenticatedTrackedPostsPostIdSettingsRouteRouteWithChildren
  '/_authenticated/followings/new/auto-comment': typeof AuthenticatedFollowingsNewAutoCommentRoute
  '/_authenticated/followings/new/monitoring': typeof AuthenticatedFollowingsNewMonitoringRoute
  '/_authenticated/followings/new/react-posts': typeof AuthenticatedFollowingsNewReactPostsRoute
  '/_authenticated/keywords/$keywordId/auto-comment': typeof AuthenticatedKeywordsKeywordIdAutoCommentRoute
  '/_authenticated/keywords/$keywordId/auto-react': typeof AuthenticatedKeywordsKeywordIdAutoReactRoute
  '/_authenticated/keywords/$keywordId/monitoring': typeof AuthenticatedKeywordsKeywordIdMonitoringRoute
  '/_authenticated/tracked-posts/new/auto-react': typeof AuthenticatedTrackedPostsNewAutoReactRoute
  '/_authenticated/tracked-posts/new/auto-reply': typeof AuthenticatedTrackedPostsNewAutoReplyRoute
  '/_authenticated/followings/new/': typeof AuthenticatedFollowingsNewIndexRoute
  '/_authenticated/keywords/$keywordId/': typeof AuthenticatedKeywordsKeywordIdIndexRoute
  '/_authenticated/tracked-posts/new/': typeof AuthenticatedTrackedPostsNewIndexRoute
  '/_authenticated/followings/$channelId/settings/auto-comment': typeof AuthenticatedFollowingsChannelIdSettingsAutoCommentRoute
  '/_authenticated/followings/$channelId/settings/monitoring': typeof AuthenticatedFollowingsChannelIdSettingsMonitoringRoute
  '/_authenticated/followings/$channelId/settings/react-posts': typeof AuthenticatedFollowingsChannelIdSettingsReactPostsRoute
  '/_authenticated/tracked-posts/$postId/settings/auto-react': typeof AuthenticatedTrackedPostsPostIdSettingsAutoReactRoute
  '/_authenticated/tracked-posts/$postId/settings/auto-reply': typeof AuthenticatedTrackedPostsPostIdSettingsAutoReplyRoute
  '/_authenticated/followings/$channelId/settings/': typeof AuthenticatedFollowingsChannelIdSettingsIndexRoute
  '/_authenticated/tracked-posts/$postId/settings/': typeof AuthenticatedTrackedPostsPostIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/magic-login'
    | '/otp'
    | '/reset-email-sent'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/magic'
    | '/followings/new'
    | '/keywords/$keywordId'
    | '/tracked-posts/new'
    | '/errors/$error'
    | '/projects/new'
    | '/settings/access'
    | '/settings/appearance'
    | '/settings/comments'
    | '/auth/google/callback'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/auto-actions/'
    | '/chats/'
    | '/followings/'
    | '/help-center/'
    | '/keywords/'
    | '/knowledge-base/'
    | '/reports/'
    | '/settings/'
    | '/sheet/'
    | '/tasks/'
    | '/tracked-posts/'
    | '/users/'
    | '/followings/$channelId/settings'
    | '/tracked-posts/$postId/settings'
    | '/followings/new/auto-comment'
    | '/followings/new/monitoring'
    | '/followings/new/react-posts'
    | '/keywords/$keywordId/auto-comment'
    | '/keywords/$keywordId/auto-react'
    | '/keywords/$keywordId/monitoring'
    | '/tracked-posts/new/auto-react'
    | '/tracked-posts/new/auto-reply'
    | '/followings/new/'
    | '/keywords/$keywordId/'
    | '/tracked-posts/new/'
    | '/followings/$channelId/settings/auto-comment'
    | '/followings/$channelId/settings/monitoring'
    | '/followings/$channelId/settings/react-posts'
    | '/tracked-posts/$postId/settings/auto-react'
    | '/tracked-posts/$postId/settings/auto-reply'
    | '/followings/$channelId/settings/'
    | '/tracked-posts/$postId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/magic-login'
    | '/otp'
    | '/reset-email-sent'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/verify-email'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/auth/magic'
    | '/'
    | '/errors/$error'
    | '/projects/new'
    | '/settings/access'
    | '/settings/appearance'
    | '/settings/comments'
    | '/auth/google/callback'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/auto-actions'
    | '/chats'
    | '/followings'
    | '/help-center'
    | '/keywords'
    | '/knowledge-base'
    | '/reports'
    | '/settings'
    | '/sheet'
    | '/tasks'
    | '/tracked-posts'
    | '/users'
    | '/followings/new/auto-comment'
    | '/followings/new/monitoring'
    | '/followings/new/react-posts'
    | '/keywords/$keywordId/auto-comment'
    | '/keywords/$keywordId/auto-react'
    | '/keywords/$keywordId/monitoring'
    | '/tracked-posts/new/auto-react'
    | '/tracked-posts/new/auto-reply'
    | '/followings/new'
    | '/keywords/$keywordId'
    | '/tracked-posts/new'
    | '/followings/$channelId/settings/auto-comment'
    | '/followings/$channelId/settings/monitoring'
    | '/followings/$channelId/settings/react-posts'
    | '/tracked-posts/$postId/settings/auto-react'
    | '/tracked-posts/$postId/settings/auto-reply'
    | '/followings/$channelId/settings'
    | '/tracked-posts/$postId/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/magic-login'
    | '/(auth)/otp'
    | '/(auth)/reset-email-sent'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/auth/magic'
    | '/_authenticated/'
    | '/_authenticated/followings/new'
    | '/_authenticated/keywords/$keywordId'
    | '/_authenticated/tracked-posts/new'
    | '/_authenticated/errors/$error'
    | '/_authenticated/projects/new'
    | '/_authenticated/settings/access'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/comments'
    | '/auth/google/callback'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/auto-actions/'
    | '/_authenticated/chats/'
    | '/_authenticated/followings/'
    | '/_authenticated/help-center/'
    | '/_authenticated/keywords/'
    | '/_authenticated/knowledge-base/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/_authenticated/sheet/'
    | '/_authenticated/tasks/'
    | '/_authenticated/tracked-posts/'
    | '/_authenticated/users/'
    | '/_authenticated/followings/$channelId/settings'
    | '/_authenticated/tracked-posts/$postId/settings'
    | '/_authenticated/followings/new/auto-comment'
    | '/_authenticated/followings/new/monitoring'
    | '/_authenticated/followings/new/react-posts'
    | '/_authenticated/keywords/$keywordId/auto-comment'
    | '/_authenticated/keywords/$keywordId/auto-react'
    | '/_authenticated/keywords/$keywordId/monitoring'
    | '/_authenticated/tracked-posts/new/auto-react'
    | '/_authenticated/tracked-posts/new/auto-reply'
    | '/_authenticated/followings/new/'
    | '/_authenticated/keywords/$keywordId/'
    | '/_authenticated/tracked-posts/new/'
    | '/_authenticated/followings/$channelId/settings/auto-comment'
    | '/_authenticated/followings/$channelId/settings/monitoring'
    | '/_authenticated/followings/$channelId/settings/react-posts'
    | '/_authenticated/tracked-posts/$postId/settings/auto-react'
    | '/_authenticated/tracked-posts/$postId/settings/auto-reply'
    | '/_authenticated/followings/$channelId/settings/'
    | '/_authenticated/tracked-posts/$postId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authMagicLoginRoute: typeof authMagicLoginRoute
  authOtpRoute: typeof authOtpRoute
  authResetEmailSentRoute: typeof authResetEmailSentRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  AuthMagicRoute: typeof AuthMagicRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/magic': {
      id: '/auth/magic'
      path: '/auth/magic'
      fullPath: '/auth/magic'
      preLoaderRoute: typeof AuthMagicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-email-sent': {
      id: '/(auth)/reset-email-sent'
      path: '/reset-email-sent'
      fullPath: '/reset-email-sent'
      preLoaderRoute: typeof authResetEmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/magic-login': {
      id: '/(auth)/magic-login'
      path: '/magic-login'
      fullPath: '/magic-login'
      preLoaderRoute: typeof authMagicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracked-posts/': {
      id: '/_authenticated/tracked-posts/'
      path: '/tracked-posts'
      fullPath: '/tracked-posts/'
      preLoaderRoute: typeof AuthenticatedTrackedPostsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sheet/': {
      id: '/_authenticated/sheet/'
      path: '/sheet'
      fullPath: '/sheet/'
      preLoaderRoute: typeof AuthenticatedSheetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-base/': {
      id: '/_authenticated/knowledge-base/'
      path: '/knowledge-base'
      fullPath: '/knowledge-base/'
      preLoaderRoute: typeof AuthenticatedKnowledgeBaseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keywords/': {
      id: '/_authenticated/keywords/'
      path: '/keywords'
      fullPath: '/keywords/'
      preLoaderRoute: typeof AuthenticatedKeywordsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followings/': {
      id: '/_authenticated/followings/'
      path: '/followings'
      fullPath: '/followings/'
      preLoaderRoute: typeof AuthenticatedFollowingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auto-actions/': {
      id: '/_authenticated/auto-actions/'
      path: '/auto-actions'
      fullPath: '/auto-actions/'
      preLoaderRoute: typeof AuthenticatedAutoActionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/comments': {
      id: '/_authenticated/settings/comments'
      path: '/comments'
      fullPath: '/settings/comments'
      preLoaderRoute: typeof AuthenticatedSettingsCommentsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/access': {
      id: '/_authenticated/settings/access'
      path: '/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof AuthenticatedSettingsAccessRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracked-posts/new': {
      id: '/_authenticated/tracked-posts/new'
      path: '/tracked-posts/new'
      fullPath: '/tracked-posts/new'
      preLoaderRoute: typeof AuthenticatedTrackedPostsNewRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keywords/$keywordId': {
      id: '/_authenticated/keywords/$keywordId'
      path: '/keywords/$keywordId'
      fullPath: '/keywords/$keywordId'
      preLoaderRoute: typeof AuthenticatedKeywordsKeywordIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followings/new': {
      id: '/_authenticated/followings/new'
      path: '/followings/new'
      fullPath: '/followings/new'
      preLoaderRoute: typeof AuthenticatedFollowingsNewRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracked-posts/new/': {
      id: '/_authenticated/tracked-posts/new/'
      path: '/'
      fullPath: '/tracked-posts/new/'
      preLoaderRoute: typeof AuthenticatedTrackedPostsNewIndexRouteImport
      parentRoute: typeof AuthenticatedTrackedPostsNewRouteRoute
    }
    '/_authenticated/keywords/$keywordId/': {
      id: '/_authenticated/keywords/$keywordId/'
      path: '/'
      fullPath: '/keywords/$keywordId/'
      preLoaderRoute: typeof AuthenticatedKeywordsKeywordIdIndexRouteImport
      parentRoute: typeof AuthenticatedKeywordsKeywordIdRouteRoute
    }
    '/_authenticated/followings/new/': {
      id: '/_authenticated/followings/new/'
      path: '/'
      fullPath: '/followings/new/'
      preLoaderRoute: typeof AuthenticatedFollowingsNewIndexRouteImport
      parentRoute: typeof AuthenticatedFollowingsNewRouteRoute
    }
    '/_authenticated/tracked-posts/new/auto-reply': {
      id: '/_authenticated/tracked-posts/new/auto-reply'
      path: '/auto-reply'
      fullPath: '/tracked-posts/new/auto-reply'
      preLoaderRoute: typeof AuthenticatedTrackedPostsNewAutoReplyRouteImport
      parentRoute: typeof AuthenticatedTrackedPostsNewRouteRoute
    }
    '/_authenticated/tracked-posts/new/auto-react': {
      id: '/_authenticated/tracked-posts/new/auto-react'
      path: '/auto-react'
      fullPath: '/tracked-posts/new/auto-react'
      preLoaderRoute: typeof AuthenticatedTrackedPostsNewAutoReactRouteImport
      parentRoute: typeof AuthenticatedTrackedPostsNewRouteRoute
    }
    '/_authenticated/keywords/$keywordId/monitoring': {
      id: '/_authenticated/keywords/$keywordId/monitoring'
      path: '/monitoring'
      fullPath: '/keywords/$keywordId/monitoring'
      preLoaderRoute: typeof AuthenticatedKeywordsKeywordIdMonitoringRouteImport
      parentRoute: typeof AuthenticatedKeywordsKeywordIdRouteRoute
    }
    '/_authenticated/keywords/$keywordId/auto-react': {
      id: '/_authenticated/keywords/$keywordId/auto-react'
      path: '/auto-react'
      fullPath: '/keywords/$keywordId/auto-react'
      preLoaderRoute: typeof AuthenticatedKeywordsKeywordIdAutoReactRouteImport
      parentRoute: typeof AuthenticatedKeywordsKeywordIdRouteRoute
    }
    '/_authenticated/keywords/$keywordId/auto-comment': {
      id: '/_authenticated/keywords/$keywordId/auto-comment'
      path: '/auto-comment'
      fullPath: '/keywords/$keywordId/auto-comment'
      preLoaderRoute: typeof AuthenticatedKeywordsKeywordIdAutoCommentRouteImport
      parentRoute: typeof AuthenticatedKeywordsKeywordIdRouteRoute
    }
    '/_authenticated/followings/new/react-posts': {
      id: '/_authenticated/followings/new/react-posts'
      path: '/react-posts'
      fullPath: '/followings/new/react-posts'
      preLoaderRoute: typeof AuthenticatedFollowingsNewReactPostsRouteImport
      parentRoute: typeof AuthenticatedFollowingsNewRouteRoute
    }
    '/_authenticated/followings/new/monitoring': {
      id: '/_authenticated/followings/new/monitoring'
      path: '/monitoring'
      fullPath: '/followings/new/monitoring'
      preLoaderRoute: typeof AuthenticatedFollowingsNewMonitoringRouteImport
      parentRoute: typeof AuthenticatedFollowingsNewRouteRoute
    }
    '/_authenticated/followings/new/auto-comment': {
      id: '/_authenticated/followings/new/auto-comment'
      path: '/auto-comment'
      fullPath: '/followings/new/auto-comment'
      preLoaderRoute: typeof AuthenticatedFollowingsNewAutoCommentRouteImport
      parentRoute: typeof AuthenticatedFollowingsNewRouteRoute
    }
    '/_authenticated/tracked-posts/$postId/settings': {
      id: '/_authenticated/tracked-posts/$postId/settings'
      path: '/tracked-posts/$postId/settings'
      fullPath: '/tracked-posts/$postId/settings'
      preLoaderRoute: typeof AuthenticatedTrackedPostsPostIdSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/followings/$channelId/settings': {
      id: '/_authenticated/followings/$channelId/settings'
      path: '/followings/$channelId/settings'
      fullPath: '/followings/$channelId/settings'
      preLoaderRoute: typeof AuthenticatedFollowingsChannelIdSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracked-posts/$postId/settings/': {
      id: '/_authenticated/tracked-posts/$postId/settings/'
      path: '/'
      fullPath: '/tracked-posts/$postId/settings/'
      preLoaderRoute: typeof AuthenticatedTrackedPostsPostIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedTrackedPostsPostIdSettingsRouteRoute
    }
    '/_authenticated/followings/$channelId/settings/': {
      id: '/_authenticated/followings/$channelId/settings/'
      path: '/'
      fullPath: '/followings/$channelId/settings/'
      preLoaderRoute: typeof AuthenticatedFollowingsChannelIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedFollowingsChannelIdSettingsRouteRoute
    }
    '/_authenticated/tracked-posts/$postId/settings/auto-reply': {
      id: '/_authenticated/tracked-posts/$postId/settings/auto-reply'
      path: '/auto-reply'
      fullPath: '/tracked-posts/$postId/settings/auto-reply'
      preLoaderRoute: typeof AuthenticatedTrackedPostsPostIdSettingsAutoReplyRouteImport
      parentRoute: typeof AuthenticatedTrackedPostsPostIdSettingsRouteRoute
    }
    '/_authenticated/tracked-posts/$postId/settings/auto-react': {
      id: '/_authenticated/tracked-posts/$postId/settings/auto-react'
      path: '/auto-react'
      fullPath: '/tracked-posts/$postId/settings/auto-react'
      preLoaderRoute: typeof AuthenticatedTrackedPostsPostIdSettingsAutoReactRouteImport
      parentRoute: typeof AuthenticatedTrackedPostsPostIdSettingsRouteRoute
    }
    '/_authenticated/followings/$channelId/settings/react-posts': {
      id: '/_authenticated/followings/$channelId/settings/react-posts'
      path: '/react-posts'
      fullPath: '/followings/$channelId/settings/react-posts'
      preLoaderRoute: typeof AuthenticatedFollowingsChannelIdSettingsReactPostsRouteImport
      parentRoute: typeof AuthenticatedFollowingsChannelIdSettingsRouteRoute
    }
    '/_authenticated/followings/$channelId/settings/monitoring': {
      id: '/_authenticated/followings/$channelId/settings/monitoring'
      path: '/monitoring'
      fullPath: '/followings/$channelId/settings/monitoring'
      preLoaderRoute: typeof AuthenticatedFollowingsChannelIdSettingsMonitoringRouteImport
      parentRoute: typeof AuthenticatedFollowingsChannelIdSettingsRouteRoute
    }
    '/_authenticated/followings/$channelId/settings/auto-comment': {
      id: '/_authenticated/followings/$channelId/settings/auto-comment'
      path: '/auto-comment'
      fullPath: '/followings/$channelId/settings/auto-comment'
      preLoaderRoute: typeof AuthenticatedFollowingsChannelIdSettingsAutoCommentRouteImport
      parentRoute: typeof AuthenticatedFollowingsChannelIdSettingsRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccessRoute: typeof AuthenticatedSettingsAccessRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsCommentsRoute: typeof AuthenticatedSettingsCommentsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccessRoute: AuthenticatedSettingsAccessRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsCommentsRoute: AuthenticatedSettingsCommentsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedFollowingsNewRouteRouteChildren {
  AuthenticatedFollowingsNewAutoCommentRoute: typeof AuthenticatedFollowingsNewAutoCommentRoute
  AuthenticatedFollowingsNewMonitoringRoute: typeof AuthenticatedFollowingsNewMonitoringRoute
  AuthenticatedFollowingsNewReactPostsRoute: typeof AuthenticatedFollowingsNewReactPostsRoute
  AuthenticatedFollowingsNewIndexRoute: typeof AuthenticatedFollowingsNewIndexRoute
}

const AuthenticatedFollowingsNewRouteRouteChildren: AuthenticatedFollowingsNewRouteRouteChildren =
  {
    AuthenticatedFollowingsNewAutoCommentRoute:
      AuthenticatedFollowingsNewAutoCommentRoute,
    AuthenticatedFollowingsNewMonitoringRoute:
      AuthenticatedFollowingsNewMonitoringRoute,
    AuthenticatedFollowingsNewReactPostsRoute:
      AuthenticatedFollowingsNewReactPostsRoute,
    AuthenticatedFollowingsNewIndexRoute: AuthenticatedFollowingsNewIndexRoute,
  }

const AuthenticatedFollowingsNewRouteRouteWithChildren =
  AuthenticatedFollowingsNewRouteRoute._addFileChildren(
    AuthenticatedFollowingsNewRouteRouteChildren,
  )

interface AuthenticatedKeywordsKeywordIdRouteRouteChildren {
  AuthenticatedKeywordsKeywordIdAutoCommentRoute: typeof AuthenticatedKeywordsKeywordIdAutoCommentRoute
  AuthenticatedKeywordsKeywordIdAutoReactRoute: typeof AuthenticatedKeywordsKeywordIdAutoReactRoute
  AuthenticatedKeywordsKeywordIdMonitoringRoute: typeof AuthenticatedKeywordsKeywordIdMonitoringRoute
  AuthenticatedKeywordsKeywordIdIndexRoute: typeof AuthenticatedKeywordsKeywordIdIndexRoute
}

const AuthenticatedKeywordsKeywordIdRouteRouteChildren: AuthenticatedKeywordsKeywordIdRouteRouteChildren =
  {
    AuthenticatedKeywordsKeywordIdAutoCommentRoute:
      AuthenticatedKeywordsKeywordIdAutoCommentRoute,
    AuthenticatedKeywordsKeywordIdAutoReactRoute:
      AuthenticatedKeywordsKeywordIdAutoReactRoute,
    AuthenticatedKeywordsKeywordIdMonitoringRoute:
      AuthenticatedKeywordsKeywordIdMonitoringRoute,
    AuthenticatedKeywordsKeywordIdIndexRoute:
      AuthenticatedKeywordsKeywordIdIndexRoute,
  }

const AuthenticatedKeywordsKeywordIdRouteRouteWithChildren =
  AuthenticatedKeywordsKeywordIdRouteRoute._addFileChildren(
    AuthenticatedKeywordsKeywordIdRouteRouteChildren,
  )

interface AuthenticatedTrackedPostsNewRouteRouteChildren {
  AuthenticatedTrackedPostsNewAutoReactRoute: typeof AuthenticatedTrackedPostsNewAutoReactRoute
  AuthenticatedTrackedPostsNewAutoReplyRoute: typeof AuthenticatedTrackedPostsNewAutoReplyRoute
  AuthenticatedTrackedPostsNewIndexRoute: typeof AuthenticatedTrackedPostsNewIndexRoute
}

const AuthenticatedTrackedPostsNewRouteRouteChildren: AuthenticatedTrackedPostsNewRouteRouteChildren =
  {
    AuthenticatedTrackedPostsNewAutoReactRoute:
      AuthenticatedTrackedPostsNewAutoReactRoute,
    AuthenticatedTrackedPostsNewAutoReplyRoute:
      AuthenticatedTrackedPostsNewAutoReplyRoute,
    AuthenticatedTrackedPostsNewIndexRoute:
      AuthenticatedTrackedPostsNewIndexRoute,
  }

const AuthenticatedTrackedPostsNewRouteRouteWithChildren =
  AuthenticatedTrackedPostsNewRouteRoute._addFileChildren(
    AuthenticatedTrackedPostsNewRouteRouteChildren,
  )

interface AuthenticatedFollowingsChannelIdSettingsRouteRouteChildren {
  AuthenticatedFollowingsChannelIdSettingsAutoCommentRoute: typeof AuthenticatedFollowingsChannelIdSettingsAutoCommentRoute
  AuthenticatedFollowingsChannelIdSettingsMonitoringRoute: typeof AuthenticatedFollowingsChannelIdSettingsMonitoringRoute
  AuthenticatedFollowingsChannelIdSettingsReactPostsRoute: typeof AuthenticatedFollowingsChannelIdSettingsReactPostsRoute
  AuthenticatedFollowingsChannelIdSettingsIndexRoute: typeof AuthenticatedFollowingsChannelIdSettingsIndexRoute
}

const AuthenticatedFollowingsChannelIdSettingsRouteRouteChildren: AuthenticatedFollowingsChannelIdSettingsRouteRouteChildren =
  {
    AuthenticatedFollowingsChannelIdSettingsAutoCommentRoute:
      AuthenticatedFollowingsChannelIdSettingsAutoCommentRoute,
    AuthenticatedFollowingsChannelIdSettingsMonitoringRoute:
      AuthenticatedFollowingsChannelIdSettingsMonitoringRoute,
    AuthenticatedFollowingsChannelIdSettingsReactPostsRoute:
      AuthenticatedFollowingsChannelIdSettingsReactPostsRoute,
    AuthenticatedFollowingsChannelIdSettingsIndexRoute:
      AuthenticatedFollowingsChannelIdSettingsIndexRoute,
  }

const AuthenticatedFollowingsChannelIdSettingsRouteRouteWithChildren =
  AuthenticatedFollowingsChannelIdSettingsRouteRoute._addFileChildren(
    AuthenticatedFollowingsChannelIdSettingsRouteRouteChildren,
  )

interface AuthenticatedTrackedPostsPostIdSettingsRouteRouteChildren {
  AuthenticatedTrackedPostsPostIdSettingsAutoReactRoute: typeof AuthenticatedTrackedPostsPostIdSettingsAutoReactRoute
  AuthenticatedTrackedPostsPostIdSettingsAutoReplyRoute: typeof AuthenticatedTrackedPostsPostIdSettingsAutoReplyRoute
  AuthenticatedTrackedPostsPostIdSettingsIndexRoute: typeof AuthenticatedTrackedPostsPostIdSettingsIndexRoute
}

const AuthenticatedTrackedPostsPostIdSettingsRouteRouteChildren: AuthenticatedTrackedPostsPostIdSettingsRouteRouteChildren =
  {
    AuthenticatedTrackedPostsPostIdSettingsAutoReactRoute:
      AuthenticatedTrackedPostsPostIdSettingsAutoReactRoute,
    AuthenticatedTrackedPostsPostIdSettingsAutoReplyRoute:
      AuthenticatedTrackedPostsPostIdSettingsAutoReplyRoute,
    AuthenticatedTrackedPostsPostIdSettingsIndexRoute:
      AuthenticatedTrackedPostsPostIdSettingsIndexRoute,
  }

const AuthenticatedTrackedPostsPostIdSettingsRouteRouteWithChildren =
  AuthenticatedTrackedPostsPostIdSettingsRouteRoute._addFileChildren(
    AuthenticatedTrackedPostsPostIdSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFollowingsNewRouteRoute: typeof AuthenticatedFollowingsNewRouteRouteWithChildren
  AuthenticatedKeywordsKeywordIdRouteRoute: typeof AuthenticatedKeywordsKeywordIdRouteRouteWithChildren
  AuthenticatedTrackedPostsNewRouteRoute: typeof AuthenticatedTrackedPostsNewRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedAutoActionsIndexRoute: typeof AuthenticatedAutoActionsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedFollowingsIndexRoute: typeof AuthenticatedFollowingsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedKeywordsIndexRoute: typeof AuthenticatedKeywordsIndexRoute
  AuthenticatedKnowledgeBaseIndexRoute: typeof AuthenticatedKnowledgeBaseIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSheetIndexRoute: typeof AuthenticatedSheetIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTrackedPostsIndexRoute: typeof AuthenticatedTrackedPostsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedFollowingsChannelIdSettingsRouteRoute: typeof AuthenticatedFollowingsChannelIdSettingsRouteRouteWithChildren
  AuthenticatedTrackedPostsPostIdSettingsRouteRoute: typeof AuthenticatedTrackedPostsPostIdSettingsRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFollowingsNewRouteRoute:
    AuthenticatedFollowingsNewRouteRouteWithChildren,
  AuthenticatedKeywordsKeywordIdRouteRoute:
    AuthenticatedKeywordsKeywordIdRouteRouteWithChildren,
  AuthenticatedTrackedPostsNewRouteRoute:
    AuthenticatedTrackedPostsNewRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedAutoActionsIndexRoute: AuthenticatedAutoActionsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedFollowingsIndexRoute: AuthenticatedFollowingsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedKeywordsIndexRoute: AuthenticatedKeywordsIndexRoute,
  AuthenticatedKnowledgeBaseIndexRoute: AuthenticatedKnowledgeBaseIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSheetIndexRoute: AuthenticatedSheetIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTrackedPostsIndexRoute: AuthenticatedTrackedPostsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedFollowingsChannelIdSettingsRouteRoute:
    AuthenticatedFollowingsChannelIdSettingsRouteRouteWithChildren,
  AuthenticatedTrackedPostsPostIdSettingsRouteRoute:
    AuthenticatedTrackedPostsPostIdSettingsRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authMagicLoginRoute: authMagicLoginRoute,
  authOtpRoute: authOtpRoute,
  authResetEmailSentRoute: authResetEmailSentRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  AuthMagicRoute: AuthMagicRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
